name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        # Основные зависимости
        sudo apt-get install -y build-essential make cmake python3 python3-pip
        # Установка Google Test
        sudo apt-get install -y libgtest-dev googletest
        # Сборка и установка GTest
        cd /usr/src/googletest
        sudo cmake CMakeLists.txt
        sudo make
        sudo make install
        # Python зависимости
        python3 -m pip install pytest

    - name: Build project
      run: make

    - name: Run C++ tests
      run: make test

    - name: Run Python tests
      run: python3 tests.py
